# Generated by Django 3.2.3 on 2021-05-27 14:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0003_auto_20210527_2007'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='userextend',
            new_name='extendeduser',
        ),
    ]
