# Generated by Django 3.2.3 on 2021-05-27 14:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0004_rename_userextend_extendeduser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='extendeduser',
            new_name='extended',
        ),
    ]
