# Generated by Django 3.2.3 on 2021-05-27 15:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0005_rename_extendeduser_extended'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='extended',
            new_name='extendeduser',
        ),
    ]
