# Generated by Django 3.2.3 on 2021-05-31 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_rename_extended_extendeduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='firstname',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='lastname',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
