# Generated by Django 3.2.3 on 2021-05-31 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20210531_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendeduser',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='extendeduser',
            name='lastname',
        ),
    ]
