# Generated by Django 3.2.3 on 2021-06-12 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20210601_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patients_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Symptom1', models.CharField(max_length=100)),
                ('Symptom2', models.CharField(max_length=100)),
                ('Symptom3', models.CharField(max_length=100)),
                ('Symptom4', models.CharField(max_length=100)),
                ('Symptom5', models.CharField(max_length=100)),
                ('suspected_Diseases', models.CharField(max_length=100)),
            ],
        ),
    ]
