# Generated by Django 3.2.3 on 2021-06-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_patients_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients_detail',
            name='Symptom1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patients_detail',
            name='Symptom2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patients_detail',
            name='Symptom3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patients_detail',
            name='Symptom4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patients_detail',
            name='Symptom5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patients_detail',
            name='suspected_Diseases',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
