# Generated by Django 3.2.3 on 2021-06-20 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20210612_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients_detail',
            name='suggested_doctor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
