# Generated by Django 3.2.3 on 2021-06-21 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='upload',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
