# Generated by Django 3.2.3 on 2021-06-28 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_patients_detail_extendeduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients_detail',
            name='extendeduser',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='website.extendeduser'),
        ),
    ]
