# Generated by Django 3.2.3 on 2021-06-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_remove_doctor_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
