# Generated by Django 3.2.3 on 2021-06-29 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0020_doctor_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients_detail',
            name='extendeduser',
        ),
        migrations.AddField(
            model_name='patients_detail',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
