# Generated by Django 3.2.3 on 2021-06-29 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_auto_20210629_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients_detail',
            name='extendeduser',
        ),
    ]
